name: build

on: push

env:
  NIGHTLY_COMMIT: a7a1618e6c835f1f00940ad72203d05808209a0d
  NIGHTLY_VERSION: '2025-07-22'
  LLVM_MAJOR: 18

jobs:
  build:
    runs-on: ${{ matrix.os }}
    container:
      image: rockylinux:9
    strategy:
      matrix:
        include:
          - arch: x86_64
            os: ubuntu-latest
          - arch: aarch64
            os: ubuntu-24.04-arm
    steps:
      - name: Install Build Dependencies
        run: |
          dnf install -yq epel-release 'dnf-command(config-manager)'
          dnf config-manager --enable crb
          dnf groupinstall -yq "Development Tools"
          dnf install -yq \
            git \
            zstd \
            xz \
            wget
          env CI=true /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install llvm@18 pkgconf cmake ninja zstd jemalloc openssl

      - name: Checkout Rust Repository
        uses: actions/checkout@v4
        with:
          repository: rust-lang/rust
          ref: ${{ env.NIGHTLY_COMMIT }}
          submodules: true

      - name: Build Rust
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          ./configure \
            --prefix=/opt/rust-nightly-${{ env.NIGHTLY_VERSION }} \
            --sysconfdir=/opt/rust-nightly-${{ env.NIGHTLY_VERSION }}/etc \
            --disable-docs \
            --enable-full-tools \
            --enable-cargo-native-static \
            --enable-llvm-link-shared \
            --llvm-root=$(brew --prefix llvm@18) \
            --set=rust.jemalloc \
            --disable-lld
          make -j$(nproc)
          make install

      - name: Verify Installation
        run: |
          /opt/rust-nightly-${{ env.NIGHTLY_VERSION }}/bin/rustc --version
          /opt/rust-nightly-${{ env.NIGHTLY_VERSION }}/bin/cargo --version

      - name: Make Archive
        run: |
          tar -cf rust-nightly-${{ env.NIGHTLY_VERSION }}-${{ matrix.arch }}.tar /opt/rust-nightly-${{ env.NIGHTLY_VERSION }}
          xz -9e -T0 rust-nightly-${{ env.NIGHTLY_VERSION }}-${{ matrix.arch }}.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust-nightly-${{ env.NIGHTLY_VERSION }}-${{ matrix.arch }}.tar.xz
          path: rust-nightly-${{ env.NIGHTLY_VERSION }}-${{ matrix.arch }}.tar.xz
          compression-level: "0"
