name: build

on: push

env:
  NIGHTLY_COMMIT: 97da04c9222b1b1b362309555c5825793c3f7f03
  NIGHTLY_VERSION: 20250722
  LLVM_MAJOR: 19

jobs:
  build:
    runs-on: ${{ matrix.os }}
    container:
      image: ubuntu:24.04
    strategy:
      matrix:
        include:
          - arch: x86_64
            os: ubuntu-latest
          - arch: aarch64
            os: ubuntu-24.04-arm
    steps:
      - name: Install Build Dependencies
        run: |
          apt-get update
          apt-get install -y \
            build-essential \
            llvm-${{ env.LLVM_MAJOR }} \
            clang-${{ env.LLVM_MAJOR }} \
            lld-${{ env.LLVM_MAJOR }} \
            cmake \
            ninja-build \
            pkg-config \
            libpolly-${{ env.LLVM_MAJOR }}-dev \
            libssl-dev \
            zlib1g-dev \
            libzstd-dev \
            zstd \
            xz-utils \
            wget \
            curl \
            git

      - name: Checkout Rust Repository
        uses: actions/checkout@v4
        with:
          repository: rust-lang/rust
          ref: ${{ env.NIGHTLY_COMMIT }}
          submodules: true

      - name: Build Rust
        run: |
          ./configure \
            --prefix=/opt/rust-nightly-${{ env.NIGHTLY_VERSION }} \
            --sysconfdir=/opt/rust-nightly-${{ env.NIGHTLY_VERSION }}/etc \
            --disable-docs \
            --disable-lld \
            --enable-full-tools \
            --enable-llvm-link-shared \
            --enable-cargo-native-static \
            --llvm-root=/usr/lib/llvm-${{ env.LLVM_MAJOR }} \
            --set=rust.jemalloc
          make -j$(nproc)
          make install

      - name: Verify Installation
        run: |
          /opt/rust-nightly-${{ env.NIGHTLY_VERSION }}/bin/rustc --version
          /opt/rust-nightly-${{ env.NIGHTLY_VERSION }}/bin/cargo --version

      - name: Make Archive
        run: |
          tar -cf rust-nightly-${{ env.NIGHTLY_VERSION }}-${{ matrix.arch }}.tar /opt/rust-nightly-${{ env.NIGHTLY_VERSION }}
          xz -9e -T0 -o rust-nightly-${{ env.NIGHTLY_VERSION }}-${{ matrix.arch }}.tar.xz rust-nightly-${{ env.NIGHTLY_VERSION }}-${{ matrix.arch }}.tar
          rm rust-nightly-${{ env.NIGHTLY_VERSION }}-${{ matrix.arch }}.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust-nightly-${{ env.NIGHTLY_VERSION }}-${{ matrix.arch }}.tar.xz
          path: rust-nightly-${{ env.NIGHTLY_VERSION }}-${{ matrix.arch }}.tar.xz
          compression-level: "0"
