name: build

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    container:
      image: ubuntu:24.04
    strategy:
      matrix:
        include:
          - arch: x86_64
            os: ubuntu-latest
          - arch: aarch64
            os: ubuntu-24.04-arm
    steps:
      - name: Install Build Dependencies
        run: |
          apt-get update
          apt-get install -y \
            build-essential \
            llvm-18 \
            clang-18 \
            lld-18 \
            cmake \
            ninja-build \
            pkg-config \
            libpolly-18-dev \
            libssl-dev \
            zlib1g-dev \
            libzstd-dev \
            zstd \
            xz-utils \
            wget \
            curl \
            git

      - name: Checkout Rust Repository
        uses: actions/checkout@v4
        with:
          repository: rust-lang/rust
          ref: 5e17a2a91dd7dbefd8b4a1087c2e42257457deeb
          submodules: true

      - name: Build Rust
        run: |
          ./configure \
            --prefix=/opt/rust-nightly-20250405 \
            --sysconfdir=/opt/rust-nightly-20250405/etc \
            --disable-docs \
            --disable-lld \
            --enable-full-tools \
            --enable-llvm-link-shared \
            --enable-cargo-native-static \
            --llvm-root=/usr/lib/llvm-18 \
            --set=rust.jemalloc
          make -j$(nproc)
          make install

      - name: Verify Installation
        run: |
          /opt/rust-nightly-20250405/bin/rustc --version
          /opt/rust-nightly-20250405/bin/cargo --version

      - name: Make Archive
        run: |
          tar -cf rust-nightly-20250405-${{ matrix.arch }}.tar /opt/rust-nightly-20250405
          pzstd --ultra -22 -o rust-nightly-20250405-${{ matrix.arch }}.tar.zst rust-nightly-20250405-${{ matrix.arch }}.tar
          rm rust-nightly-20250405-${{ matrix.arch }}.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust-nightly-20250405-${{ matrix.arch }}.tar.zst
          path: rust-nightly-20250405-${{ matrix.arch }}.tar.zst
          compression-level: "0"
